spring:
  profiles:
    active: dev


logging:
  level:
    net:
      engineeringdigest:
        journalApp:
          service:
            UserService: OFF


weather:
  api:
    key: 6f866b011c4ccdb8fbcdd1aa073fc264